name: Deploy Website

# Run this workflow on every push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the default Actions token
          publish_dir: .  # Publish from the root folder
          publish_branch: main  # Deploy to the main branch for user/organization pages
